server:
  port: 10336

spring:
  application:
    name: byeol23-gateway
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true # ?? ???? ???
    gateway:
      server:
        webflux:
          routes:
            - id: byeol23-backend
              uri: lb://byeol23-backend
              predicates:
                - Path=/api/**
            - id: byeol23-auth
              uri: lb://byeol23-auth
              predicates:
                - Path=/auth/**
            - id: byeol23-search
              uri: lb://byeol23-search
              predicates:
                - Path=/search-api/**
              filters:
                - StripPrefix=1

logging:
  level:
    root: info

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10338/dashboard/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: [health, info]

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiNJoRcPJmLQ7Ii+hv78J
    NhtSgo7w7u8TS3PsftAMKBvkqpeAInmnpra1usEPhXTVWOyLLxL6yJAymKY8lzDf
    3I74T0F4GJiomkjjOdIT5TEAc5X3um+IuHxu7Qapr0BuKwBvT4FCBJ9jzPOCq8xk
    h2q/AWGfOTlPLjBmAVnp2NbbV4aI5cQR6D9a/extPX6hhAtq/NZqE665L/SVIXqP
    abu2Owpvn90O6HtNXzg6ytk7Rj4FBx6YLtqHy0QAf8/o/Zc1nr+ZHwSsDQ+am6Sp
    2ZmUl03ScerF7EMtfZyzUqY46RFNgUkhB7iJb2hZ3xYGtR9SUI+PDvt2Kz6AETew
    hQIDAQAB
    -----END PUBLIC KEY-----